### ISSUE TITLE
Please tell more about arguments for --fbset flag

### ISSUE THREAD

**Issue by cipher387** [gsvprharsha/Br0ther_Ey3#1]

**Comment by gsvprharsha** [comment]
Hi

Thank you for raising the bug. 

"fbset" is the flag that will initiate scan for only websites owned by FB. As of 28/06/2022; there are only 2 websites that the tool is programmed to scan. More websites will definitely be added in a few days time. **The script right now has been updated and it mentions the same.**

Thanks again for raising this issue. Do consider trying out the tool and if any bugs; you can raise an issue and I will try to fix it asap.
